'use client';
import { useState } from 'react';
import PrimaryButton from './PrimaryButton';

/** Displays the protected invoice decision and invokes the sandbox deny path. */
export default function DemoConsole({ compact = false }: { compact?: boolean }) {
  const [decision, setDecision] = useState('waiting');
  const run = async () => { setDecision('checking'); try { const response = await fetch('/api/demo/invoice', { method: 'POST', headers: { 'content-type': 'application/json' }, body: JSON.stringify({ invoiceId: 'northwind-042' }) }); const data = await response.json(); setDecision(data.reason || data.result || 'sandbox'); } catch { setDecision('sandbox'); } };
  return <div className="p-2 rounded-[1rem] bg-[var(--bg-secondary)] ring-1 ring-[var(--border-default)]"><div className="rounded-[calc(1rem-0.5rem)] bg-[var(--bg-surface)] p-5 md:p-6 liquid-glass-light"><div className="flex items-center justify-between mb-4"><span className="font-mono text-[11px] uppercase tracking-[.18em] text-[var(--text-muted)]">Latch · pay.lock</span><span className="inline-flex items-center gap-2 font-mono text-[11px] text-[var(--success)]"><span className="w-1.5 h-1.5 rounded-full bg-[var(--success)] pulse-dot" />sandbox</span></div><div>{[['Payee','{{vendor.iban}}'],['Amount','4,250.00 USDC'],['Decision',decision]].map(([label,value]) => <div key={label} className="flex items-start justify-between gap-4 py-3 border-t border-[var(--border-subtle)] first:border-t-0 first:pt-0"><span className="font-mono text-[11px] uppercase tracking-[.14em] text-[var(--text-muted)]">{label}</span><span className={`font-mono text-sm text-right ${value === 'payee_mismatch' ? 'text-[var(--error)]' : 'text-[var(--text-primary)]'}`}>{value}</span></div>)}</div>{!compact && <button onClick={run} className="mt-5 w-full h-10 rounded-full bg-[var(--accent)] text-[var(--bg-primary)] text-sm focus-visible:outline focus-visible:outline-2 focus-visible:outline-offset-2 focus-visible:outline-[var(--accent)]">Run the invoice</button>}</div></div>;
}
